#!/usr/bin/env bash

set -Eeu

LibraryPATH=(
    "/usr/lib/"
    "/lib/"
    "${HOME}/.local/lib/"
)

FileName="fasbashlib.sh"
FileName_SnakeCase="fasbashlib-snake.sh"
UseSnakeCase=false
ExitCode=1
SourceMode=false

PrintArray(){
    (( $# >= 1 )) || return 0
    printf "%s\n" "${@}"
}

ForEach(){
    local _Item
    while read -r _Item; do
        "${@//"{}"/"${_Item}"}"| return "${?}"
    done
}

TextBox(){
    local _Content=() _Length _Vertical="|" _Line="="
    readarray -t _Content
    _Length="$(PrintArray "${_Content[@]}" | awk '{ if ( length > x ) { x = length } }END{ print x }')"
    echo "${_Vertical}${_Line}$(yes "${_Line}" | head -n "$_Length" | tr -d "\n")${_Vertical}"
    for _Str in "${_Content[@]}"; do
        echo "${_Vertical}${_Str}$(yes " " | head -n "$(( _Length + 1 - "${#_Str}"))" | tr -d "\n")${_Vertical}"
    done
    echo "${_Vertical}${_Line}$(yes "${_Line}" | head -n "$_Length" | tr -d "\n")${_Vertical}"
}

HelpDoc(){
    {
        echo " <Fasbashlib local path finder>"
        echo " Return installed FasBashLib PATH"
        echo " The library must have a specific name"
        echo
        echo " Usage: ${0} <version>"
        echo
        echo " Options:"
        echo "     -h    Show this message"
        echo "     -p    Add library dir"
        echo "     -x    Script source mode"
        echo "     -s    Enable snake case (Find $FileName_SnakeCase )"
        echo
        echo " Support filename:"
        printf "           %s/${FileName}\n" "${LibraryPATH[@]%/}"
        printf "           %s/${FileName_SnakeCase}\n" "${LibraryPATH[@]%/}"
    } | TextBox
}

while getopts hp:sx OPT;do
    case "${OPT}" in
        p)
            LibraryPATH+=("${OPTARG}")
            ;;
        h)
            HelpDoc
            ;;
        x)
            SourceMode=true
            ;;
        s)
            UseSnakeCase=true
            ;;
        *)
            HelpDoc
            exit 1
            ;;
    esac
done

shift $((OPTIND - 1))

RequireVersion="${1-""}"


if [[ "${UseSnakeCase}" = true ]]; then
    FileName="${FileName_SnakeCase}"
fi

for Dir in "${LibraryPATH[@]}"; do
    LibPath="${Dir%/}/${FileName}"
    [[ -e "$LibPath" ]] || continue
    LibVersion=$(
        # shellcheck source=/dev/null
        source "$LibPath"
        echo "${FSBLIB_VERSION}"
    )
    if [[ -n "${RequireVersion-""}" ]] && [[ ! "$LibVersion" = "${RequireVersion}"* ]]; then
        continue
    fi
    if [[ "$SourceMode" = true ]]; then
        cat "$LibPath"
    else
        echo "${LibPath}"
    fi
    exit 0
done

exit 1
