#!/usr/bin/env bash

set -euo pipefail

TMPDIR="${TMPDIR:-/tmp}"
current_dir="$( cd "$( dirname "${0}" )" && pwd )"
out_dir="$current_dir/out"
build_target=()
meta_filename="target.json"

find(){
    if { command find --help 2>/dev/null || true; } | grep -q "GNU" 1>/dev/null; then
        command find "$@"
    elif which gfind 1>/dev/null 2>&1; then
        command gfind "$@"
    else
        echo "No GNU find found"
        return 1
    fi
}

get_build_target(){
    find "$current_dir" -name "${meta_filename}" -type f -print0 | xargs -0 -I{} bash -c 'dirname {}'
}

get_header(){
    local target="$1" headers=()
    readarray -t headers < <(jq -r ".headers[]" "$target/${meta_filename}")
    while read -r script; do
        if [ -e "${target}/$script" ]; then
            echo "Header $script found" >&2
            cat "${target}/$script"
        else
            echo "Header script $script not found" >&2
            return 1
        fi
    done < <(printf '%s\n' "${headers[@]}")
    
}

get_footer(){
    local target="$1" footers=()
    readarray -t footers < <(jq -r ".footers[]" "$target/${meta_filename}")
    for script in "${footers[@]}"; do
        if [ -e "${target}/$script" ]; then
            echo "Footer $script found" >&2
            cat "${target}/$script"
        else
            echo "Footer script $script not found" >&2
            return 1
        fi
    done | grep -Ev " *#!/usr/bin/env bash" || true
    return 0
}

get_func(){
    local target="$1" funcfiles=()
    readarray -t funcfiles < <(jq -r ".functions[]" "$target/${meta_filename}")
    (
        local func
        while read -r func; do
            unset -f "$func"
        done <<< "$(typeset -F | awk '{print $3}')"
        while read -r script; do
            if [ -e "$script" ]; then
                #shellcheck source=/dev/null
                source "$script" || {
                    echo "Failed to source $script"
                    return 1
                }
            else
                echo "Function script $script not found"
                return 1
            fi
        done < <(printf "${target}/%s\\n" "${funcfiles[@]}")

        typeset -f
    )

}

unset_allfunc(){
    local func
    while read -r func; do
        unset -f "$func"
    done < <(typeset -F | awk '{print $3}')
}

get_funclist(){
    local target="$1" funcfiles=()
    readarray -t funcfiles < <(jq -r ".functions[]" "$target/${meta_filename}")
    (
        unset_allfunc
        while read -r script; do
            if [ -e "$script" ]; then
                #shellcheck source=/dev/null
                source "$script" || {
                    echo "Failed to source $script"
                    return 1
                }
            else
                echo "Function script $script not found"
                return 1
            fi
        done <<< "$(printf "${target}/%s\\n" "${funcfiles[@]}")"

        typeset -F | awk '{print $3}'
    )
}

make_entrypoint(){
    local target="$1" entrypoint
    entrypoint="$(jq -r ".entrypoint" "$target/${meta_filename}")"
    get_funclist "$target" | grep -qx "$entrypoint" || {
        echo "Entrypoint $entrypoint function are not defined" >&2
        return 1
    }
    # shellcheck disable=SC2016
    printf '%s "${@}"\n' "$entrypoint"
}

print_array(){
    (( $# == 0 )) && return 0
    printf '%s\n' "$@"
}

print_eval_array(){
    eval "print_array \"\${${1}[@]}\""
}

insert_remote(){
    local target="$1" insert_keywords=() base_script=() key
    readarray -t base_script
    readarray -t insert_keywords < <(jq -r '.["remote-inserts"] | keys[]' "$target/${meta_filename}")
    if (( ${#insert_keywords[@]} == 0 )); then
        print_array "${base_script[@]}"
        return 0
    fi
    for key in "${insert_keywords[@]}"; do
        local insert_url
        echo "Inserting $key" >&2
        insert_url="$(jq -r ".[\"remote-inserts\"][\"$key\"]" "$target/${meta_filename}")"
        if [[ -n "$insert_url" ]]; then
            #readarray -t remote_file < <(curl -s "$insert_url")
            #print_array "${remote_file[@]}" > 
            curl -sLf "$insert_url" > "$TMPDIR/remote_insert" || {
                echo "Failed to download $insert_url" >&2
                echo "Please check $key in ${target}/${meta_filename}" >&2
                return 1
            }
            readarray -t base_script< <(print_array "${base_script[@]}" | sed "/^${key}$/r $TMPDIR/remote_insert" | sed "/^${key}$/d")
        fi
    done
    print_array "${base_script[@]}"
}

get_remote_func(){
    local url target="$1"
    while read -r url; do
        (
            unset_allfunc
            #shellcheck source=/dev/null
            source <(curl -s "$url") || {
                echo "Failed to source $url" >&2
                return 1
            }
            typeset -f
        )
    done < <(jq -r '.["remote-functions"][]' "$target/${meta_filename}")
}

call(){
    echo "call: $*" >&2
    "$@"
}

build(){
    local target="$1"
    {
        call get_header "$target"
        call get_remote_func "$target"
        call get_func "$target" 
        call make_entrypoint "$target"
        call get_footer "$target"
    } | insert_remote "$target" | shfmt
}

get_filename(){
    local target="$1"
    jq -r ".filename" "$target/${meta_filename}"
}



while getopts "C:o:" OPT; do
  case "$OPT" in
    C)
        current_dir="$OPTARG"
        ;;
    o)
        out_dir="$OPTARG"
        ;;
    *)
        echo "Usage: $0 [-C]" >&2
        exit 1
        ;;
  esac
done

shift "$((OPTIND - 1))"

if (( $# > 0 )); then
    build_target=("$@")
else
    readarray -t build_target < <(get_build_target)
fi

echo "Build: ${build_target[*]}" >&2

for target in "${build_target[@]}"; do
    if [[ "$(basename "$target")" = "$meta_filename" ]]; then
        if [[ -e "${target}" ]]; then
            readarray -t build_target < <(printf '%s\n' "${build_target[@]}" | sed "s|^${target}$|$(dirname "${target}")|g")
        else
            echo "Target $target is not found" >&2
            exit 1
        fi
    elif ! [[ -e "${target}/${meta_filename}" ]]; then
        echo "Target ${target}/${meta_filename} is not found" >&2
        exit 1
    fi
done

mkdir -p "${out_dir}"

for target in "${build_target[@]}"; do
    echo "Building $target" >&2
    build "${target}" > "${out_dir}/$(get_filename "${target}")"
    chmod +x "${out_dir}/$(get_filename "${target}")"
done
