# このGitHub Actionsはhayao0819/hayao.fascode.net上でのみ実行されます
name: Build dev branch

on: 
  push:
    branches:
      - dev

jobs:
  build-dev:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0 
    
      - name: Build
        run: |
          make
          make docs

      - name: Upload built files
        uses: actions/upload-artifact@v2
        with:
          name: FasBashLib
          path: |
            ./fasbashlib.sh
            ./docs/*
