# このGitHub Actionsはhayao0819/hayao.fascode.net上でのみ実行されます
name: Build dev branch

on: 
  push:
    branches:
      - dev

jobs:
  build-dev:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0 

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.GH_PAGES_REPO_DEPLOY_KEY }}
          name: id_rsa # optional
          known_hosts: unnecessary

      - name: Commit files to build-dev
        env: 
          GH_PAGES_REPO_DEPLOY_KEY: ${{ secrets.GH_PAGES_REPO_DEPLOY_KEY }}
        run: |
          echo "$GH_PAGES_REPO_DEPLOY_KEY" > ~/deploy_key.pem
          chmod 600 ~/deploy_key.pem
          git config --local user.email "hayao@fascode.net"
          git config --local user.name "hayao[bot]"
          git config pull.rebase false
          make
          make docs
          git add -f ./fasbashlib.sh ./docs/*
          git commit -m "Build Update $(date "+%Y/%m/%d|%T")"
          git checkout -b build-dev
          git push --set-upstream origin build-dev
