name: Build dev branch

on: 
  push:
    branches:
      - dev

jobs:
  build-dev:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0 

      - name: Build
        run: |
          make
          make docs

      - name: Upload built files
        uses: actions/upload-artifact@v2
        with:
          name: FasBashLib
          path: ./fasbashlib.sh

      - name: Upload built files
        uses: actions/upload-artifact@v2
        with:
          name: FasBashLib Documents
          path: ./docs/*

      - name: Commit library to another branch
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          # Optional, but recommended
          # Defaults to "Apply automatic changes"
          commit_message: Update fasbashlib.sh

          # Optional branch name where commit should be pushed to.
          # Defaults to the current branch.
          branch: build-dev

          # Optional. Used by `git-commit`.
          # See https://git-scm.com/docs/git-commit#_options
          commit_options: '--no-verify --signoff'

          # Optional glob pattern of files which should be added to the commit
          # Defaults to all (.)
          # See the `pathspec`-documentation for git
          # - https://git-scm.com/docs/git-add#Documentation/git-add.txt-ltpathspecgt82308203
          # - https://git-scm.com/docs/gitglossary#Documentation/gitglossary.txt-aiddefpathspecapathspec
          file_pattern: ./docs/* ./fasbashlib.sh

          # Optional. Used by `git-add`
          # See https://git-scm.com/docs/git-add#_options
          add_options: '-u --force'

          # Optional. Used by `git-push`
          # See https://git-scm.com/docs/git-push#_options
          #push_options: '--force'
          
          # Optional. Disable dirty check and always try to create a commit and push
          skip_dirty_check: true    
          
          # Optional. Skip internal call to `git fetch`
          skip_fetch: true    
          
          # Optional. Skip internal call to `git checkout`
          skip_checkout: true

          # Optional. Prevents the shell from expanding filenames. 
          # Details: https://www.gnu.org/software/bash/manual/html_node/Filename-Expansion.html
          disable_globbing: true
