name: Build dev branch

on: 
  push:
    branches:
      - dev

jobs:
  build-dev:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0 

      - name: Build
        run: |
          make
          make docs

      - name: Upload built files
        uses: actions/upload-artifact@v2
        with:
          name: FasBashLib
          path: ./fasbashlib.sh

      - name: Upload built files
        uses: actions/upload-artifact@v2
        with:
          name: FasBashLib Documents
          path: ./docs/*

      - name: Commit library to another branch
        uses: EndBug/add-and-commit@v8.0.2
        with:
          # The arguments for the `git add` command (see the paragraph below for more info)
          # Default: '.'
          add: './fasbashlib.sh'

          # The name of the user that will be displayed as the author of the commit.
          # Default: depends on the default_author input
          author_name: hayao[bot]

          # The email of the user that will be displayed as the author of the commit.
          # Default: depends on the default_author input
          author_email: hayao@fascode.net

          # Additional arguments for the git commit command. The --message argument is already set by the message input.
          # Default: ''
          commit: --signoff


          # Determines the way the action fills missing author name and email. Three options are available:
          # - github_actor -> UserName <UserName@users.noreply.github.com>
          # - user_info -> Your Display Name <your-actual@email.com>
          # - github_actions -> github-actions <email associated with the github logo>
          # Default: github_actor
          default_author: github_actor

          # The message for the commit.
          # Default: 'Commit from GitHub Actions (name of the workflow)'
          message: 'Update fasbashlib.sh'

          # If this input is set, the action will push the commit to a new branch with this name.
          # Default: ''
          new_branch: dev-build

          # The way the action should handle pathspec errors from the add and remove commands. Three options are available:
          # - ignore -> errors will be logged but the step won't fail
          # - exitImmediately -> the action will stop right away, and the step will fail
          # - exitAtEnd -> the action will go on, every pathspec error will be logged at the end, the step will fail.
          # Default: ignore
          pathspec_error_handling: ignore

          # Arguments for the git pull command. By default, the action does not pull.
          # Default: ''
          pull: '--rebase --autostash ...'

          # Whether to push the commit and, if any, its tags to the repo. It can also be used to set the git push arguments (see the paragraph below for more info)
          # Default: true
          push: true



