name: Build dev branch

on: 
  workflow_dispatch:
  push:
    branches:
      - dev-0.1.x

jobs:
  build-01x:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0 

      - name: Build
        run: |
          make
          make docs

      - name: Upload built files
        uses: actions/upload-artifact@v2
        with:
          name: FasBashLib
          path: ./fasbashlib.sh

      - name: Upload built files
        uses: actions/upload-artifact@v2
        with:
          name: FasBashLib Documents
          path: ./docs/*

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.GH_PAGES_REPO_DEPLOY_KEY }}
          name: id_rsa # optional
          known_hosts: unnecessary

      - name: Prepare for commit
        env: 
          GH_PAGES_REPO_DEPLOY_KEY: ${{ secrets.GH_PAGES_REPO_DEPLOY_KEY }}
          PUSH_BRANCH: build-0.1.x
        run: |
          echo "$GH_PAGES_REPO_DEPLOY_KEY" > ~/deploy_key.pem
          chmod 600 ~/deploy_key.pem
          git config --local user.email "hayao@fascode.net"
          git config --local user.name "hayao[bot]"
          git config pull.rebase false
          git config remote.origin.url "git@github.com:Hayao0819/FasBashLib.git"
          echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
          git pull --allow-unrelated-histories origin "${PUSH_BRANCH}"
          git checkout -b "${PUSH_BRANCH}"
          
      - name: Run commit
        run: |
          make
          make docs
          rm -rf .gitignore && echo "Removed .gitignore"
          git add --force ./docs/ ./fasbashlib.sh
          git commit -m "Update: Updated built docs and fasbashlib.sh (${GITHUB_SHA})" || true
          git push --force origin "${PUSH_BRANCH}"
    