name: Test library

on: 
  push:
    #branches:
    #  - dev-0.1.x
  workflow_dispatch:

jobs:
  check-lib:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0 

      - name: Test library
        run: make test
